language: python
python:
  - "3.8"

before_install:
  - sudo apt -y install python3-distutils python3-pip git zip unzip openjdk-8-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

install:
  - git clone https://github.com/kivy/buildozer.git
  - cd buildozer
  - python3 setup.py install
  - cd ..

before_script:
  - export PATH=$PATH:~/.local/bin/
  - cp buildozer-32bit.spec buildozer.spec
  - travis_wait 20 buildozer android debug
  - gem install dpl --pre

script:
  - dpl releases --token $GITHUB_TOKEN --file "bin/mortgagecalculator-0.1-armeabi-v7a-debug.apk" --tag_name "v.0.1"
  - rm -r -f .buildozer
  - cp buildozer-64bit.spec buildozer.spec
  - travis_wait 20 buildozer android debug
  - dpl releases --token $GITHUB_TOKEN --file "bin/mortgagecalculator-0.1-arm64-v8a-debug.apk" --tag_name "v.0.1"
